backend:
  name: github
  repo: bottlehs/gatsby-starter-company-blog
  branch: main
  base_url: https://api.netlify.com
  site_domain: gatsby-starter-company-blog.netlify.app
  auth_endpoint: auth
  api_root: https://api.github.com

media_folder: static/assets
public_folder: /assets

collections:
  - name: news
    label: News
    folder: content/posts/blog/news
    create: true
    slug: 'news/{{slug}}/index'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'draft', name: 'draft', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Writer', name: 'writer', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: 'Image size 550x550 works best :)'
        required: false
        media_library:
          config:
            multiple: false
  - name: tech
    label: Tech
    folder: content/posts/blog/tech
    create: true
    slug: 'tech/{{slug}}/index'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'draft', name: 'draft', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Writer', name: 'writer', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: 'Image size 550x550 works best :)'
        required: false
        media_library:
          config:
            multiple: false
